@baseUrl = http://localhost:3333/api
// @authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@test.com",
  "password": "passwordTest123"
}

###
# @name create_pet
POST {{baseUrl}}/pet
Content-Type: application/json

{
  "name": "Nina",
  "type": "CAT"
}

###
# @name create-adoption
POST {{baseUrl}}/adoption
Content-Type: application/json

{
  "userId": "d3896795-8d8b-437a-bafb-b8d5d7b75a4b",
  "petId": "f1e64533-033a-4f85-9171-308fc8715c3a"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "passwordTest123"
}

# ###
# # @name create_question
# POST {{baseUrl}}/questions
# Content-Type: application/json
# Authorization: Bearer {{authToken}}

# {
#   "title": "New question 2",
#   "content": "Content question"
# }

# ###
# # @name get_question
# GET {{baseUrl}}/questions?page=2
# Content-Type: application/json
# Authorization: Bearer {{authToken}}
