@baseUrl = http://localhost:3333/api
// @authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Barretadao",
  "email": "john.barretoaasdasdd@test.com",
  "password": "passwordTest123"
}

###
# @name create_pet
POST {{baseUrl}}/pet
Content-Type: application/json

{
  "name": "Pituxa",
  "type": "cat"
}

###
# @name create-adoption
POST {{baseUrl}}/adoption
Content-Type: application/json

{
  "userId": "db484282-84bd-4c68-8db2-5f3541c091ae",
  "petId": "c9ede3b6-eeed-4eb3-8e6a-036a459460a0"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "passwordTest123"
}

# ###
# # @name create_question
# POST {{baseUrl}}/questions
# Content-Type: application/json
# Authorization: Bearer {{authToken}}

# {
#   "title": "New question 2",
#   "content": "Content question"
# }

# ###
# # @name get_question
# GET {{baseUrl}}/questions?page=2
# Content-Type: application/json
# Authorization: Bearer {{authToken}}
