@baseUrl = http://localhost:3333/api
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@test.com",
  "password": "passwordTest123"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john.doe@test.com",
  "password": "passwordTest123"
}

###
# @name create_pet
POST {{baseUrl}}/pet
Content-Type: application/json

{
  "name": "Dora",
  "type": "CAT"
}

###
# @name create-adoption
POST {{baseUrl}}/adoption
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "petId": "bcf740e7-569f-4beb-9275-f5881c6334a7"
}
